apiVersion: k3d.io/v1alpha4
kind: Simple
servers: 1 # same as `--servers 1`
agents: 2 # same as `--agents 2`
ports:
  - port: 8070:80 # same as `--port '8070:90@loadbalancer'` # http default
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
